import { DataTypes } from "sequelize";
import { sequelize } from '../config/db.js';

const User = sequelize.define(
  "User",
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    first_name: { type: DataTypes.STRING(150), allowNull: true },
    last_name: { type: DataTypes.STRING(150), allowNull: true },
    gender: { type: DataTypes.STRING(10), allowNull: true },
    bio: { type: DataTypes.TEXT("medium"), allowNull: true },
    website: { type: DataTypes.STRING(255), allowNull: true },
    dob: { type: DataTypes.DATEONLY, allowNull: true },
    social_id: { type: DataTypes.STRING(255), allowNull: true },
    email: { type: DataTypes.STRING(150), allowNull: true, unique: true },
    phone: { type: DataTypes.STRING(255), allowNull: true },
    password: { type: DataTypes.STRING(500), allowNull: false },
    profile_pic: { type: DataTypes.STRING(255), allowNull: true },
    profile_pic_small: { type: DataTypes.STRING(255), allowNull: true },
    profile_gif: { type: DataTypes.STRING(255), allowNull: true },
    profile_video: { type: DataTypes.STRING(255), allowNull: true },
    role: { type: DataTypes.STRING(10), allowNull: true },
    username: { type: DataTypes.STRING(255), allowNull: false, unique: true },
    social: { type: DataTypes.STRING(255), allowNull: true },
    device_token: { type: DataTypes.STRING(255), allowNull: true },
    token: { type: DataTypes.STRING(255), allowNull: true },
    active: { type: DataTypes.INTEGER, defaultValue: 1 },
    lat: { type: DataTypes.STRING(255), allowNull: true },
    long: { type: DataTypes.STRING(255), allowNull: true },
    online: { type: DataTypes.INTEGER, defaultValue: 0 },
    verified: { type: DataTypes.INTEGER, defaultValue: 0 },
    auth_token: { type: DataTypes.STRING(255), allowNull: true },
    version: { type: DataTypes.STRING(255), allowNull: true },
    device: { type: DataTypes.STRING(255), allowNull: true },
    ip: { type: DataTypes.STRING(255), allowNull: true },
    city: { type: DataTypes.STRING(255), allowNull: true },
    country: { type: DataTypes.STRING(255), allowNull: true },
    state: { type: DataTypes.STRING(255), allowNull: true },
    region: { type: DataTypes.STRING(255), allowNull: true },
    location_string: { type: DataTypes.STRING(255), allowNull: true },
    country_id: { type: DataTypes.INTEGER, allowNull: true },
    wallet: { type: DataTypes.INTEGER, defaultValue: 0 },
    paypal: { type: DataTypes.STRING(255), allowNull: true },
    private: { type: DataTypes.INTEGER, defaultValue: 0 },
    profile_view: { type: DataTypes.INTEGER, defaultValue: 0 },
    reset_wallet_datetime: { type: DataTypes.DATE, allowNull: true },
    last_wallet: { type: DataTypes.INTEGER, allowNull: true },
    referral_code: { type: DataTypes.STRING(255), allowNull: true },
    register_with: { type: DataTypes.STRING(255), allowNull: true },
    stripe_customer_id: { type: DataTypes.STRING(255), allowNull: true },
    created: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    parent: { type: DataTypes.INTEGER, allowNull: true },
    salt: { type: DataTypes.STRING(255), allowNull: true },
    post_video_notification: { type: DataTypes.INTEGER, defaultValue: 1 },
    city_id: { type: DataTypes.INTEGER, allowNull: true },
    state_id: { type: DataTypes.INTEGER, allowNull: true },
    shadow_ban: { type: DataTypes.INTEGER, defaultValue: 0 },
    business: { type: DataTypes.INTEGER, defaultValue: 0 },
  },
  {
    tableName: "user",
    timestamps: false, // custom created column only
  }
);

export default User;
